language: node_js

node_js:
  - stable

before_install:
  npm i -g ionic cordova

install:
  npm install

script:
  npm run ionic:build --

notifications:
  email:
    on_success: never
    on_failure: always
