version: 2
jobs:
  build:
    branches:
      ignore: gh-pages
    working_directory: ~/repo
    docker:
      - image: node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "./clinet/package.json" }}
      - run:
          name: install ionic
          command: npm install -g ionic cordova
      - run:
          name: npm install
          command: cd client && npm install
      - run:
          name: ionic build browser
          command: cd client && npm run ionic:build --
      - save_cache:
          key: dependency-cache-{{ checksum "./clinet/package.json" }}
          paths:
            - ./client/node_modules
      - deploy:
          name: Deploy
          command: |
              if [ "${CIRCLE_BRANCH}" == "ionic" ]; then
                git config --global user.email "${GH_EMAIL}"
                git config --global user.name "${GH_NAME}"
                sh deploy-gh.sh
              fi
